// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyC3QnruW1CjZeZgasqI7kLZ6gPIg4eHI',
    appId: '1:844195824522:web:8619b3ba88574b02d4be73',
    messagingSenderId: '844195824522',
    projectId: 'chat-app-d3c64',
    authDomain: 'chat-app-d3c64.firebaseapp.com',
    storageBucket: 'chat-app-d3c64.appspot.com',
    measurementId: 'G-6Q0GGZQ14R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6h4w12CfW_SDVTf_jXbZr7JxSA-mm5aQ',
    appId: '1:844195824522:android:429eb5c7f5cb721ad4be73',
    messagingSenderId: '844195824522',
    projectId: 'chat-app-d3c64',
    storageBucket: 'chat-app-d3c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3JcUIREZ5shXKU8bjp5zRdiWUvFdsF1A',
    appId: '1:844195824522:ios:a16aa02d16f14769d4be73',
    messagingSenderId: '844195824522',
    projectId: 'chat-app-d3c64',
    storageBucket: 'chat-app-d3c64.appspot.com',
    iosClientId: '844195824522-l5qfgtlh1vpf8i4fvgerjgrfu1ljtmlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3JcUIREZ5shXKU8bjp5zRdiWUvFdsF1A',
    appId: '1:844195824522:ios:a16aa02d16f14769d4be73',
    messagingSenderId: '844195824522',
    projectId: 'chat-app-d3c64',
    storageBucket: 'chat-app-d3c64.appspot.com',
    iosClientId: '844195824522-l5qfgtlh1vpf8i4fvgerjgrfu1ljtmlq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
